<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="manip_6_dof" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="w1" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="l0" value="1" /> <!-- Link 3 -->
  <xacro:property name="l1" value="0.25" /> <!-- Link 1 -->
  <xacro:property name="l2" value="1" /> <!-- Link 2 -->
  <xacro:property name="l3" value="0.75" /> <!-- Link 3 -->
  <xacro:property name="l4" value="0.25" /> <!-- Link 3 -->
  <xacro:property name="l5" value="0.125" /> <!-- Link 3 -->
  <xacro:property name="l6" value="0.05" /> <!-- Link 3 -->
  <xacro:property name="r0" value="0.25" /> <!-- Link 3 -->
  <xacro:property name="r6" value="0.05" /> <!-- Link 3 -->
  <xacro:property name="l_palm" value="0.25" /> <!-- Link 3 -->
  <xacro:property name="w_palm" value="0.05" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find manip_6_dof)/src/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find manip_6_dof)/src/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="base" type="fixed">
    <parent link="world"/>
    <child link="l0"/>
  </joint>

  <!-- Base Link -->
  <link name="l0">
    <collision>
      <origin xyz="0 0 ${l0/2}" rpy="0 0 0"/>
      <geometry>
  <cylinder length="${l0}" radius="${r0}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l0/2}" rpy="0 0 0"/>
      <geometry>
  <cylinder length="${l0}" radius="${r0}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l0/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

  <joint name="j1" type="revolute">
    <parent link="l0"/>
    <child link="l1"/>
    <origin xyz="0 0 ${l0}" rpy="0 0 0"/>
    <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>



  <link name="l1">
    <collision>
      <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
      <geometry>
  <cylinder length="${l1}" radius="${r0}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
      <geometry>
  <cylinder length="${l1}" radius="${r0}" />
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

  <joint name="j2" type="revolute">
    <parent link="l1"/>
    <child link="l2"/>
    <origin xyz="0 ${r0+w1/2} ${l1/2}" rpy="0 0 0"/>
    <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>

    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="l2">
    <collision>
      <origin xyz="0 0 ${l2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l2}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>


<joint name="j3" type="revolute">
    <parent link="l2"/>
    <child link="l3"/>
    <origin xyz="0 ${w1} ${l2 - axel_offset*2}" rpy="0 0 0"/>
    <limit effort="1000.0" lower="-3" upper="3" velocity="0.5"/>

    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="l3">
    <collision>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l3}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

<joint name="j4" type="revolute">
    <parent link="l3"/>
    <child link="l4"/>
    <origin xyz="0 0 ${l3 - w1/2}" rpy="0 0 0"/>
    <limit effort="1000.0" lower="0.0" upper="3.15" velocity="0.5"/>

    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="l4">
    <collision>
      <origin xyz="0 0 ${l4/2 }" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l4}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l4/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l4}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l4/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

  <joint name="j5" type="revolute">
    <parent link="l4"/>
    <child link="l5"/>
    <origin xyz="${w1} 0 ${l4-w1/2}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="-2.5" upper="2.5" velocity="0.5"/>

    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="l5">
    <collision>
      <origin xyz="0 0 ${l5/2 -w1/2 }" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l5}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l5/2 -w1/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${w1} ${w1} ${l5}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l5/2-w1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>

  </link>

  <joint name="j6" type="revolute">
    <parent link="l5"/>
    <child link="l6"/>
    <origin xyz="0 0 ${l5-w1/2}" rpy="0 0 1.57"/>
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.5"/>

    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="l6">

  <collision>
    <origin xyz="0 0 ${l6/2 }" rpy="0 0 0"/>
    <geometry>
<cylinder length="${l6}" radius="${r6}" />
    </geometry>
  </collision>

  <visual>
    <origin xyz="0 0 ${l6/2}" rpy="0 0 0"/>
    <geometry>
<cylinder length="${l6}" radius="${r6}" />
    </geometry>
    <material name="black"/>
  </visual>

  <inertial>
    <origin xyz="0 0 ${l6/2}" rpy="0 0 0"/>
    <mass value="${mass}"/>
    <inertia
  ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
  iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
  izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
  </inertial>
  </link>

  <joint name = "griper" type="fixed">
    <parent link="l6"/>
    <child link="arm_palm"/>
    <origin xyz="0 0 ${l6}" rpy="0 0 0"/>
  </joint>

  <link name="arm_palm">
    <collision>
      <origin xyz="0 0 ${w_palm/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${l_palm} ${w_palm} ${w_palm}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${w_palm/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${l_palm} ${w_palm} ${w_palm}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

  <joint name = "L_finger" type="prismatic">
    <parent link="arm_palm"/>
    <child link="LF"/>
    <origin xyz="${l_palm/2 - w_palm/2} 0 ${w_palm}" rpy="0 0 3.14"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="0" upper="${l_palm/3}" velocity="0.5"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="LF">
    <collision>
      <origin xyz="0 0 ${l_palm/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${w_palm} ${w_palm} ${l_palm}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l_palm/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${w_palm} ${w_palm} ${l_palm}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>

  <joint name = "R_finger" type="prismatic">
    <parent link="arm_palm"/>
    <child link="RF"/>
    <origin xyz="${-l_palm/2 + w_palm/2} 0 ${w_palm}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="0" upper="${l_palm/3}" velocity="0.5"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="RF">
    <collision>
      <origin xyz="0 0 ${l_palm/2}" rpy="0 0 0"/>
      <geometry>
  <box size="${w_palm} ${w_palm} ${l_palm}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${l_palm/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${w_palm} ${w_palm} ${l_palm}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${l3/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
    ixx="${mass / 12.0 * (w1*w1 + l1*l1)}" ixy="0.0" ixz="0.0"
    iyy="${mass / 12.0 * (l1*l1 + w1*w1)}" iyz="0.0"
    izz="${mass / 12.0 * (w1*w1 + w1*w1)}"/>
    </inertial>
  </link>













  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
    <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
    <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
    <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j5">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="j6">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
